AWSTemplateFormatVersion: '2010-09-09'
Description: Create an S3 Bucket

Resources:
  MyS3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: my-unique-bucket-name

Outputs:
  S3BucketName:
    Description: The name of the created S3 bucket
    Value: !Ref MyS3Bucket
