version: '3.9'

services:
  web:
    image: my-python-app  # Replace with the image name for your Python application
    ports:
      - "5000:80"
    depends_on:
      - db
  db:
    image: postgres
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
